#!/usr/bin/env python
# -*- coding: utf-8 -*-


# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 1

build:
  image: testing
  os: ubuntu-20.04
  tools:
    python: "3.10"


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: true


python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - pip3 install -r requirements.txt
    - python3 setup.py build_ext --inplace
    - pip3 install .
